import 'package:flutter/material.dart';

class SearchNotesScreen extends StatelessWidget {
  const SearchNotesScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text('Search Notes'),
                              ),
                                    body: Padding(
                                            padding: const EdgeInsets.all(20),
                                                    child: Column(
                                                              crossAxisAlignment: CrossAxisAlignment.start,
                                                                        children: [
                                                                                    const Text(
                                                                                                  'Find Your Notes',
                                                                                                                style: TextStyle(
                                                                                                                                fontSize: 26,
                                                                                                                                                fontWeight: FontWeight.bold,
                                                                                                                                                              ),
                                                                                                                                                                          ),
                                                                                                                                                                                      const SizedBox(height: 20),
                                                                                                                                                                                                  TextField(
                                                                                                                                                                                                                decoration: InputDecoration(
                                                                                                                                                                                                                                hintText: 'Search subject or unit',
                                                                                                                                                                                                                                                prefixIcon: const Icon(Icons.search),
                                                                                                                                                                                                                                                                border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                  borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 25),
                                                                                                                                                                                                                                                                                                                                                    const Text(
                                                                                                                                                                                                                                                                                                                                                                  'Subjects',
                                                                                                                                                                                                                                                                                                                                                                                style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                leading: const Icon(Icons.menu_book),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: const Text('Mathematics'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                subtitle: const Text('Unit 1 • Unit 2 • Unit 3'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    leading: const Icon(Icons.menu_book),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: const Text('Computer Science'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    subtitle: const Text('Unit 1 • Unit 2 • Unit 3'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            