import 'package:flutter/material.dart';

class YearSubjectsScreen extends StatelessWidget {
  final String year;

    const YearSubjectsScreen({
        super.key,
            required this.year,
              });

                @override
                  Widget build(BuildContext context) {
                      final subjects = [
                            'Mathematics',
                                  'Computer Science',
                                        'Physics',
                                              'Chemistry',
                                                    'English',
                                                          'Communication Skills',
                                                              ];

                                                                  return Scaffold(
                                                                        appBar: AppBar(
                                                                                title: Text('$year Subjects'),
                                                                                      ),
                                                                                            body: Padding(
                                                                                                    padding: const EdgeInsets.all(20),
                                                                                                            child: Column(
                                                                                                                      crossAxisAlignment: CrossAxisAlignment.start,
                                                                                                                                children: [
                                                                                                                                            Text(
                                                                                                                                                          '$year Subjects',
                                                                                                                                                                        style: const TextStyle(
                                                                                                                                                                                        fontSize: 26,
                                                                                                                                                                                                        fontWeight: FontWeight.bold,
                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                              const SizedBox(height: 20),
                                                                                                                                                                                                                                                          Expanded(
                                                                                                                                                                                                                                                                        child: ListView.builder(
                                                                                                                                                                                                                                                                                        itemCount: subjects.length,
                                                                                                                                                                                                                                                                                                        itemBuilder: (context, index) {
                                                                                                                                                                                                                                                                                                                          return Card(
                                                                                                                                                                                                                                                                                                                                              child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                    leading: const Icon(Icons.menu_book),
                                                                                                                                                                                                                                                                                                                                                                                          title: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                  subjects[index],
                                                                                                                                                                                                                                                                                                                                                                                                                                          style: const TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  trailing: const Icon(Icons.arrow_forward_ios),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onTap: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }